- platform: mqtt
  name: 'MQTT switch'
  state_topic: "home/bedroom/switch"
  command_topic: "home/bedroom/switch/set"

  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
    